package com.aistareco.aep.clip.controller;

import com.aistareco.aep.clip.dto.ClipDtos.*;
import com.aistareco.aep.clip.dto.ClipRequests.*;
import com.aistareco.aep.clip.security.ClipServiceIdentity;
import com.aistareco.aep.clip.service.*;
import com.aistareco.common.ApiResponse;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;
import java.util.*;

/** 军师 BFF 专用 clip facade：service token 鉴权，externalOwnerId 是所有属主查询真源。 */
@RestController
@RequestMapping("/api/me/clip")
public class ClipController {
    private final ClipServiceIdentity identity;private final ClipTemplateService templates;private final ClipProjectService projects;
    private final ClipScriptService scripts;private final ClipEstimateService estimates;private final ClipRenderService renders;
    private final ClipAssetService assets;private final ClipWorkService works;private final ClipAvatarService avatars;private final ClipUploadService uploads;
    public ClipController(ClipServiceIdentity identity,ClipTemplateService templates,ClipProjectService projects,ClipScriptService scripts,ClipEstimateService estimates,ClipRenderService renders,ClipAssetService assets,ClipWorkService works,ClipAvatarService avatars,ClipUploadService uploads){this.identity=identity;this.templates=templates;this.projects=projects;this.scripts=scripts;this.estimates=estimates;this.renders=renders;this.assets=assets;this.works=works;this.avatars=avatars;this.uploads=uploads;}
    private String owner(String auth,String owner,String tenant){return identity.require(auth,owner,tenant).externalOwnerId();}

    @GetMapping("/templates") public ApiResponse<List<TemplateDto>> templates(@RequestHeader(value="Authorization",required=false)String a,@RequestHeader(value="X-External-Owner-Id",required=false)String o,@RequestHeader(value="X-External-Tenant-Id",required=false)String t){owner(a,o,t);return ApiResponse.of(templates.published());}
    @GetMapping("/templates/{id}") public ApiResponse<TemplateDto> template(@RequestHeader(value="Authorization",required=false)String a,@RequestHeader(value="X-External-Owner-Id",required=false)String o,@RequestHeader(value="X-External-Tenant-Id",required=false)String t,@PathVariable String id){owner(a,o,t);return ApiResponse.of(templates.published(id));}

    @PostMapping("/projects") public ApiResponse<ProjectDto> create(@RequestHeader(value="Authorization",required=false)String a,@RequestHeader(value="X-External-Owner-Id",required=false)String o,@RequestHeader(value="X-External-Tenant-Id",required=false)String t,@RequestBody CreateProject r){return ApiResponse.of(projects.create(owner(a,o,t),r.templateId()));}
    @GetMapping("/projects") public ApiResponse<List<ProjectDto>> projects(@RequestHeader(value="Authorization",required=false)String a,@RequestHeader(value="X-External-Owner-Id",required=false)String o,@RequestHeader(value="X-External-Tenant-Id",required=false)String t){return ApiResponse.of(projects.list(owner(a,o,t)));}
    @GetMapping("/projects/ongoing") public ApiResponse<ProjectDto> ongoing(@RequestHeader(value="Authorization",required=false)String a,@RequestHeader(value="X-External-Owner-Id",required=false)String o,@RequestHeader(value="X-External-Tenant-Id",required=false)String t){return ApiResponse.of(projects.ongoing(owner(a,o,t)));}
    @GetMapping("/projects/{id}") public ApiResponse<ProjectDto> project(@RequestHeader(value="Authorization",required=false)String a,@RequestHeader(value="X-External-Owner-Id",required=false)String o,@RequestHeader(value="X-External-Tenant-Id",required=false)String t,@PathVariable String id){return ApiResponse.of(projects.get(owner(a,o,t),id));}
    @PutMapping("/projects/{id}") public ApiResponse<ProjectDto> save(@RequestHeader(value="Authorization",required=false)String a,@RequestHeader(value="X-External-Owner-Id",required=false)String o,@RequestHeader(value="X-External-Tenant-Id",required=false)String t,@PathVariable String id,@RequestBody SaveProject r){return ApiResponse.of(projects.save(owner(a,o,t),id,r));}
    @DeleteMapping("/projects/{id}") public ApiResponse<Map<String,Object>> delete(@RequestHeader(value="Authorization",required=false)String a,@RequestHeader(value="X-External-Owner-Id",required=false)String o,@RequestHeader(value="X-External-Tenant-Id",required=false)String t,@PathVariable String id){projects.softDelete(owner(a,o,t),id);return ApiResponse.of(Map.of("ok",true));}
    @PostMapping("/projects/{id}/restore") public ApiResponse<ProjectDto> restore(@RequestHeader(value="Authorization",required=false)String a,@RequestHeader(value="X-External-Owner-Id",required=false)String o,@RequestHeader(value="X-External-Tenant-Id",required=false)String t,@PathVariable String id){return ApiResponse.of(projects.restore(owner(a,o,t),id));}
    @PostMapping("/projects/{id}/purge") public ApiResponse<Map<String,Object>> purge(@RequestHeader(value="Authorization",required=false)String a,@RequestHeader(value="X-External-Owner-Id",required=false)String o,@RequestHeader(value="X-External-Tenant-Id",required=false)String t,@PathVariable String id){projects.purge(owner(a,o,t),id);return ApiResponse.of(Map.of("ok",true));}
    @PostMapping("/projects/{id}/script/reset") public ApiResponse<Map<String,Object>> reset(@RequestHeader(value="Authorization",required=false)String a,@RequestHeader(value="X-External-Owner-Id",required=false)String o,@RequestHeader(value="X-External-Tenant-Id",required=false)String t,@PathVariable String id){return ApiResponse.of(projects.reset(owner(a,o,t),id));}
    @PostMapping("/projects/{id}/script/ai-rewrite") public ApiResponse<Map<String,Object>> rewrite(@RequestHeader(value="Authorization",required=false)String a,@RequestHeader(value="X-External-Owner-Id",required=false)String o,@RequestHeader(value="X-External-Tenant-Id",required=false)String t,@PathVariable String id,@RequestBody Rewrite r){return ApiResponse.of(scripts.rewrite(owner(a,o,t),id,r.scope(),r.no(),r.text()));}
    @PostMapping("/projects/{id}/preview-voice") public ApiResponse<Map<String,Object>> preview(@RequestHeader(value="Authorization",required=false)String a,@RequestHeader(value="X-External-Owner-Id",required=false)String o,@RequestHeader(value="X-External-Tenant-Id",required=false)String t,@PathVariable String id,@RequestBody PreviewVoice r){return ApiResponse.of(scripts.preview(owner(a,o,t),id,r.no(),r.text()));}
    @PostMapping("/projects/{id}/estimate") public ApiResponse<EstimateDto> estimate(@RequestHeader(value="Authorization",required=false)String a,@RequestHeader(value="X-External-Owner-Id",required=false)String o,@RequestHeader(value="X-External-Tenant-Id",required=false)String t,@PathVariable String id,@RequestBody(required=false) Estimate r){return ApiResponse.of(estimates.estimate(owner(a,o,t),id,r==null?null:r.segments(),r==null?null:r.shots()));}
    @PostMapping("/projects/{id}/render") public ApiResponse<RenderResult> render(@RequestHeader(value="Authorization",required=false)String a,@RequestHeader(value="X-External-Owner-Id",required=false)String o,@RequestHeader(value="X-External-Tenant-Id",required=false)String t,@PathVariable String id,@RequestBody Render r){return ApiResponse.of(renders.render(owner(a,o,t),id,r.clientRequestId(),r.externalCreditsHeld()));}
    @GetMapping("/jobs/{id}") public ApiResponse<JobDto> job(@RequestHeader(value="Authorization",required=false)String a,@RequestHeader(value="X-External-Owner-Id",required=false)String o,@RequestHeader(value="X-External-Tenant-Id",required=false)String t,@PathVariable String id){return ApiResponse.of(renders.get(owner(a,o,t),id));}
    @PostMapping("/jobs/{id}/cancel") public ApiResponse<JobDto> cancel(@RequestHeader(value="Authorization",required=false)String a,@RequestHeader(value="X-External-Owner-Id",required=false)String o,@RequestHeader(value="X-External-Tenant-Id",required=false)String t,@PathVariable String id){return ApiResponse.of(renders.cancel(owner(a,o,t),id));}

    @GetMapping("/assets") public ApiResponse<List<AssetDto>> assets(@RequestHeader(value="Authorization",required=false)String a,@RequestHeader(value="X-External-Owner-Id",required=false)String o,@RequestHeader(value="X-External-Tenant-Id",required=false)String t){return ApiResponse.of(assets.list(owner(a,o,t)));}
    // extraQuotaBytes = 用户买到的扩容**增量**（军师侧的钻石扩容包合计）。默认额度在本服务，
    // 扩容权益在军师，各报各知道的那一半 —— 谁也不用复制对方的常量。调用方持服务令牌，可信。
    @GetMapping("/assets/storage") public ApiResponse<AssetStorageDto> assetStorage(@RequestHeader(value="Authorization",required=false)String a,@RequestHeader(value="X-External-Owner-Id",required=false)String o,@RequestHeader(value="X-External-Tenant-Id",required=false)String t,@RequestParam(required=false,defaultValue="0")long extraQuotaBytes){return ApiResponse.of(assets.storage(owner(a,o,t),extraQuotaBytes));}
    /** width/height 是端上 wx.chooseMedia 报的像素尺寸，**只作服务端 ffprobe 失败时的兜底**（见 ClipAssetService.upload）。 */
    @PostMapping("/assets") public ApiResponse<AssetDto> upload(@RequestHeader(value="Authorization",required=false)String a,@RequestHeader(value="X-External-Owner-Id",required=false)String o,@RequestHeader(value="X-External-Tenant-Id",required=false)String t,@RequestParam(required=false,defaultValue="0")long extraQuotaBytes,@RequestPart("file")MultipartFile file,@RequestParam(defaultValue="video")String kind,@RequestParam(required=false)String label,@RequestParam(required=false)Integer width,@RequestParam(required=false)Integer height){return ApiResponse.of(assets.upload(owner(a,o,t),file,kind,label,false,null,width,height,extraQuotaBytes));}
    @PatchMapping("/assets/{id}") public ApiResponse<AssetDto> updateAsset(@RequestHeader(value="Authorization",required=false)String a,@RequestHeader(value="X-External-Owner-Id",required=false)String o,@RequestHeader(value="X-External-Tenant-Id",required=false)String t,@PathVariable String id,@RequestBody UpdateAsset r){return ApiResponse.of(assets.update(owner(a,o,t),id,r.label(),r.tag()));}
    @DeleteMapping("/assets/{id}") public ApiResponse<Map<String,Object>> deleteAsset(@RequestHeader(value="Authorization",required=false)String a,@RequestHeader(value="X-External-Owner-Id",required=false)String o,@RequestHeader(value="X-External-Tenant-Id",required=false)String t,@PathVariable String id){assets.delete(owner(a,o,t),id);return ApiResponse.of(Map.of("ok",true));}

    @GetMapping("/works") public ApiResponse<List<WorkDto>> works(@RequestHeader(value="Authorization",required=false)String a,@RequestHeader(value="X-External-Owner-Id",required=false)String o,@RequestHeader(value="X-External-Tenant-Id",required=false)String t){return ApiResponse.of(works.list(owner(a,o,t)));}
    @GetMapping("/works/{id}") public ApiResponse<WorkDto> work(@RequestHeader(value="Authorization",required=false)String a,@RequestHeader(value="X-External-Owner-Id",required=false)String o,@RequestHeader(value="X-External-Tenant-Id",required=false)String t,@PathVariable String id){return ApiResponse.of(works.get(owner(a,o,t),id));}
    @DeleteMapping("/works/{id}") public ApiResponse<Map<String,Object>> deleteWork(@RequestHeader(value="Authorization",required=false)String a,@RequestHeader(value="X-External-Owner-Id",required=false)String o,@RequestHeader(value="X-External-Tenant-Id",required=false)String t,@PathVariable String id){List<String> cancelledJobIds=works.delete(owner(a,o,t),id);return ApiResponse.of(Map.of("ok",true,"cancelledJobIds",cancelledJobIds));}
    @PostMapping("/works/{id}/publish") public ApiResponse<Map<String,Object>> publish(@RequestHeader(value="Authorization",required=false)String a,@RequestHeader(value="X-External-Owner-Id",required=false)String o,@RequestHeader(value="X-External-Tenant-Id",required=false)String t,@PathVariable String id,@RequestBody Publish r){return ApiResponse.of(works.publish(owner(a,o,t),id,r.platform()));}

    @GetMapping("/avatar") public ApiResponse<AvatarDto> avatar(@RequestHeader(value="Authorization",required=false)String a,@RequestHeader(value="X-External-Owner-Id",required=false)String o,@RequestHeader(value="X-External-Tenant-Id",required=false)String t){return ApiResponse.of(avatars.view(owner(a,o,t)));}
    @GetMapping("/avatars") public ApiResponse<List<AvatarDto>> avatars(@RequestHeader(value="Authorization",required=false)String a,@RequestHeader(value="X-External-Owner-Id",required=false)String o,@RequestHeader(value="X-External-Tenant-Id",required=false)String t){return ApiResponse.of(avatars.list(owner(a,o,t)));}
    @GetMapping("/avatars/{id}") public ApiResponse<AvatarDto> avatar(@RequestHeader(value="Authorization",required=false)String a,@RequestHeader(value="X-External-Owner-Id",required=false)String o,@RequestHeader(value="X-External-Tenant-Id",required=false)String t,@PathVariable String id){return ApiResponse.of(avatars.view(owner(a,o,t),id));}
    @GetMapping("/voices") public ApiResponse<List<VoiceDto>> voices(@RequestHeader(value="Authorization",required=false)String a,@RequestHeader(value="X-External-Owner-Id",required=false)String o,@RequestHeader(value="X-External-Tenant-Id",required=false)String t){return ApiResponse.of(avatars.voiceList(owner(a,o,t)));}
    /** 单条声音状态。只训了声音、没建形象的用户靠这条拿终态 —— 形象视图那条路径覆盖不到他们。 */
    @GetMapping("/voices/{id}") public ApiResponse<VoiceDto> voice(@RequestHeader(value="Authorization",required=false)String a,@RequestHeader(value="X-External-Owner-Id",required=false)String o,@RequestHeader(value="X-External-Tenant-Id",required=false)String t,@PathVariable String id){return ApiResponse.of(avatars.voiceView(owner(a,o,t),id));}
    @GetMapping("/avatar/requirements") public ApiResponse<CaptureRequirementsDto> avatarRequirements(@RequestHeader(value="Authorization",required=false)String a,@RequestHeader(value="X-External-Owner-Id",required=false)String o,@RequestHeader(value="X-External-Tenant-Id",required=false)String t){owner(a,o,t);return ApiResponse.of(avatars.requirements());}
    @PostMapping("/avatar/consent") public ApiResponse<ConsentDto> consent(@RequestHeader(value="Authorization",required=false)String a,@RequestHeader(value="X-External-Owner-Id",required=false)String o,@RequestHeader(value="X-External-Tenant-Id",required=false)String t,@RequestPart("file")MultipartFile file,@RequestParam String text){return ApiResponse.of(avatars.startConsent(owner(a,o,t),file,text));}
    /** 这条声音还剩几次免费重训（官方每条给 4 次，且不消耗克隆权益）。只在重训页调一次，不进列表接口。 */
    @PostMapping("/voices/{id}/preview") public ApiResponse<VoicePreviewDto> previewVoice(@RequestHeader(value="Authorization",required=false)String a,@RequestHeader(value="X-External-Owner-Id",required=false)String o,@RequestHeader(value="X-External-Tenant-Id",required=false)String t,@PathVariable String id,@RequestBody java.util.Map<String,String> body){return ApiResponse.of(avatars.previewVoice(owner(a,o,t),id,body==null?null:body.get("text")));}
    @GetMapping("/voices/{id}/retrain-quota") public ApiResponse<Map<String,Object>> retrainQuota(@RequestHeader(value="Authorization",required=false)String a,@RequestHeader(value="X-External-Owner-Id",required=false)String o,@RequestHeader(value="X-External-Tenant-Id",required=false)String t,@PathVariable String id){return ApiResponse.of(avatars.retrainQuota(owner(a,o,t),id));}
    @PatchMapping("/voices/{id}") public ApiResponse<VoiceDto> renameVoice(@RequestHeader(value="Authorization",required=false)String a,@RequestHeader(value="X-External-Owner-Id",required=false)String o,@RequestHeader(value="X-External-Tenant-Id",required=false)String t,@PathVariable String id,@RequestBody java.util.Map<String,String> body){return ApiResponse.of(avatars.renameVoice(owner(a,o,t),id,body==null?null:body.get("name")));}
    @PostMapping("/avatar/clone") public ApiResponse<Map<String,Object>> clone(@RequestHeader(value="Authorization",required=false)String a,@RequestHeader(value="X-External-Owner-Id",required=false)String o,@RequestHeader(value="X-External-Tenant-Id",required=false)String t,@RequestPart("file")MultipartFile file,@RequestParam String kind,@RequestParam(required=false)String avatarId,@RequestParam(required=false)String voiceId,@RequestParam(required=false)String name,@RequestParam(required=false)String voiceSource){return ApiResponse.of(avatars.clone(owner(a,o,t),kind,file,avatarId,voiceId,name,voiceSource));}
    @PostMapping("/avatar/uploads") public ApiResponse<CloneUploadTicketDto> createUpload(@RequestHeader(value="Authorization",required=false)String a,@RequestHeader(value="X-External-Owner-Id",required=false)String o,@RequestHeader(value="X-External-Tenant-Id",required=false)String t,@RequestBody CreateCloneUpload r){return ApiResponse.of(uploads.issue(owner(a,o,t),r));}
    @PostMapping("/avatar/uploads/{id}/complete") public ApiResponse<CloneUploadStatusDto> completeUpload(@RequestHeader(value="Authorization",required=false)String a,@RequestHeader(value="X-External-Owner-Id",required=false)String o,@RequestHeader(value="X-External-Tenant-Id",required=false)String t,@PathVariable String id){return ApiResponse.of(uploads.complete(owner(a,o,t),id));}
    @PostMapping("/avatar/uploads/{id}/submit") public ApiResponse<CloneUploadStatusDto> submitUpload(@RequestHeader(value="Authorization",required=false)String a,@RequestHeader(value="X-External-Owner-Id",required=false)String o,@RequestHeader(value="X-External-Tenant-Id",required=false)String t,@PathVariable String id,@RequestBody SubmitCloneUpload r){return ApiResponse.of(uploads.submit(owner(a,o,t),id,r));}
    @GetMapping("/avatar/uploads/{id}") public ApiResponse<CloneUploadStatusDto> uploadStatus(@RequestHeader(value="Authorization",required=false)String a,@RequestHeader(value="X-External-Owner-Id",required=false)String o,@RequestHeader(value="X-External-Tenant-Id",required=false)String t,@PathVariable String id){return ApiResponse.of(uploads.status(owner(a,o,t),id));}
    @GetMapping("/avatar/consents") public ApiResponse<List<AuditDto>> consents(@RequestHeader(value="Authorization",required=false)String a,@RequestHeader(value="X-External-Owner-Id",required=false)String o,@RequestHeader(value="X-External-Tenant-Id",required=false)String t){return ApiResponse.of(avatars.consentLogs(owner(a,o,t)));}
    @GetMapping("/avatar/usages") public ApiResponse<List<AuditDto>> usages(@RequestHeader(value="Authorization",required=false)String a,@RequestHeader(value="X-External-Owner-Id",required=false)String o,@RequestHeader(value="X-External-Tenant-Id",required=false)String t){return ApiResponse.of(avatars.usageLogs(owner(a,o,t)));}
    @DeleteMapping("/avatar") public ApiResponse<Map<String,Object>> deleteAvatar(@RequestHeader(value="Authorization",required=false)String a,@RequestHeader(value="X-External-Owner-Id",required=false)String o,@RequestHeader(value="X-External-Tenant-Id",required=false)String t){avatars.delete(owner(a,o,t));return ApiResponse.of(Map.of("ok",true));}
    @DeleteMapping("/avatars/{id}") public ApiResponse<Map<String,Object>> deleteAvatar(@RequestHeader(value="Authorization",required=false)String a,@RequestHeader(value="X-External-Owner-Id",required=false)String o,@RequestHeader(value="X-External-Tenant-Id",required=false)String t,@PathVariable String id){avatars.delete(owner(a,o,t),id);return ApiResponse.of(Map.of("ok",true));}
}
