package db.migration;
import org.flywaydb.core.api.migration.*;

/** New endpoint policy and durable tickets; existing endpoints remain unlimited. */
public class V48__endpoint_generation_queue extends BaseJavaMigration {
    @Override public void migrate(Context context) throws Exception {
        try(var s=context.getConnection().createStatement()) {
            s.executeUpdate("ALTER TABLE ai_model_providers ADD COLUMN concurrency_limit INT NULL");
            boolean mysql=context.getConnection().getMetaData().getDatabaseProductName().toLowerCase().contains("mysql");
            s.executeUpdate("CREATE TABLE ai_generation_queue (id BIGINT "+(mysql?"AUTO_INCREMENT":"GENERATED BY DEFAULT AS IDENTITY")+" PRIMARY KEY, endpoint_id VARCHAR(64) NOT NULL, task_type VARCHAR(32) NOT NULL, task_id VARCHAR(64) NOT NULL, state VARCHAR(16) NOT NULL, created_at TIMESTAMP(6) NOT NULL, dispatch_after TIMESTAMP(6) NOT NULL, CONSTRAINT uk_ai_generation_task UNIQUE(task_type,task_id))");
            s.executeUpdate("CREATE INDEX idx_ai_generation_queue_endpoint ON ai_generation_queue(endpoint_id,state,id)");
        }
    }
}
