'use client';
import { useEffect,useLayoutEffect,useMemo,useState } from 'react';
import { Button,Input,Modal,Select } from 'antd';
import { ArrowLeft,ChevronLeft,ChevronRight,Search,UserRound,Volume2 } from 'lucide-react';
import type { StudioIpAsset,StudioIpAssetRole,StudioVoiceCatalog,StudioVoiceProfile } from '@ai-star-eco/types/ip-studio-workflow';
import { SignedImage } from '@/canvas-bridge/signed-image';
import { SignedAudio } from '@/canvas-bridge/signed-audio';
import { classifyStudioIpAsset,studioVoiceProfiles } from '@/canvas-bridge/studio-api';
import { editableIpAssetRoles,filterStudioCharacters,groupStudioIpAssets,ipAssetIdentity,ipAssetRole,ipAssetRoles } from '@/canvas-bridge/studio-ip-library';
import { studioOverlayContainer } from './studio-overlay';

type Props={actionLabel?:string;open:boolean;assets:StudioIpAsset[];loading:boolean;error:string;onClose:()=>void;onRefresh:()=>void;onImport:(asset:StudioIpAsset,voice?:StudioVoiceProfile)=>Promise<void>;onAssetChange:(asset:StudioIpAsset)=>void};
const container=studioOverlayContainer;
export function StudioIpLibrary({actionLabel,open,assets,loading,error,onClose,onRefresh,onImport,onAssetChange}:Props) {
  const [search,setSearch]=useState(''),[path,setPath]=useState('all'),[source,setSource]=useState<'mine'|'official'>('mine'),[role,setRole]=useState('all'),[attribute,setAttribute]=useState<string>();
  const [personId,setPersonId]=useState<string>(),[selectedId,setSelectedId]=useState<string>(),[busy,setBusy]=useState(false),[actionError,setActionError]=useState('');
  const [importing,setImporting]=useState(false);
  const [voices,setVoices]=useState<StudioVoiceCatalog>(),[voiceError,setVoiceError]=useState(''),[voiceLoading,setVoiceLoading]=useState(false),[voiceRevision,setVoiceRevision]=useState(0);
  useLayoutEffect(()=>{if(!open)return;setPersonId(undefined);setSelectedId(undefined);setActionError('');},[open]);
  useEffect(()=>{if(!open)return;let active=true;setVoices(undefined);setVoiceError('');setVoiceLoading(true);void studioVoiceProfiles().then(v=>{if(active)setVoices(v);}).catch(e=>{if(active)setVoiceError(e.message||'声音暂未读取');}).finally(()=>{if(active)setVoiceLoading(false);});return()=>{active=false;};},[open,voiceRevision]);
  const characters=useMemo(()=>groupStudioIpAssets(assets),[assets]);
  const attributeOptions=useMemo(()=>{const values=new Set<string>();for(const c of characters)for(const key of ['性别','年龄','时代','纪元','风格'])if(c.main.attributes?.[key])values.add(`${key}\u0000${c.main.attributes[key]}`);return [...values].map(value=>({value,label:value.replace('\u0000',' · ')}));},[characters]);
  const sourceCharacters=characters.filter(c=>(c.main.librarySource||'mine')===source);
  const shown=filterStudioCharacters(sourceCharacters,search,path,role,attribute?attribute.split('\u0000') as [string,string]:undefined);
  const person=characters.find(c=>c.id===personId),index=shown.findIndex(c=>c.id===personId);
  const selected=person?.assets.find(a=>ipAssetIdentity(a)===selectedId)||person?.main;
  const performer=voices?.performers.find(p=>p.avatarId===personId),voice=voices?.profiles.find(v=>v.avatarId===personId&&v.voiceId===performer?.voiceId);
  const openPerson=(id:string)=>{setPersonId(id);setSelectedId(undefined);setActionError('');};
  const pick=(asset:StudioIpAsset)=>setSelectedId(ipAssetIdentity(asset));
  const importSelected=async()=>{if(!selected||busy)return;setBusy(true);setImporting(true);setActionError('');try{await onImport(selected,voice);}catch(e){setActionError(e instanceof Error?e.message:'素材未添加，请重试');}finally{setBusy(false);setImporting(false);}};
  const classify=async(value:StudioIpAssetRole)=>{if(!selected?.lookId||busy)return;setBusy(true);setActionError('');try{onAssetChange(await classifyStudioIpAsset(selected.avatarId,selected.lookId,value));}catch(e){setActionError(e instanceof Error?e.message:'分类未保存');}finally{setBusy(false);}};
  const visual=(title:string,roles:StudioIpAssetRole[],wide=false)=>{const items=person?.assets.filter(a=>roles.includes(ipAssetRole(a)))||[];return <section className={`studio-character-section${wide?' studio-character-wide':''}`} aria-label={title}><h3>{title}<span>{items.length?`${items.length} 张`:'未添加'}</span></h3>{items.length?<div className="studio-character-strip">{items.map(a=><button type="button" key={ipAssetIdentity(a)} className={selected&&ipAssetIdentity(selected)===ipAssetIdentity(a)?'is-selected':''} aria-pressed={!!selected&&ipAssetIdentity(selected)===ipAssetIdentity(a)} aria-label={`选择${a.name} · ${ipAssetRoles[ipAssetRole(a)]}`} disabled={busy} onClick={()=>pick(a)}><SignedImage src={a.url} storageKey={a.storageKey} alt={a.name}/><span>{a.name}</span></button>)}</div>:<div className="studio-character-missing">{title}素材将在归档后显示</div>}</section>;};
  return <Modal open={open} onCancel={busy?undefined:onClose} closable={!busy} title="IP 人物库" centered footer={null} width="min(1280px, calc(100vw - 48px))" className="studio-ip-library-modal" getContainer={container} styles={{container:{padding:0,overflow:"hidden"},header:{display:"none"},body:{padding:0}}} destroyOnHidden>
    <div className="studio-library-shell">
      <aside className="studio-library-sidebar"><h2><UserRound size={19}/>IP 人物库</h2><p>人物与可复用素材</p><nav aria-label="IP 库来源">{([['mine','我的 IP'],['official','官方 IP']] as const).map(([value,label])=><button type="button" key={value} disabled={busy} aria-pressed={source===value} onClick={()=>{setSource(value);setPersonId(undefined);}}>{label}<span>{characters.filter(c=>(c.main.librarySource||'mine')===value).length}</span></button>)}</nav><div className="studio-library-sidebar-note">主形象、设定图、视角和声音<br/>都归在同一个人物下</div></aside>
      <main className="studio-library-main">
        <header className="studio-library-toolbar"><strong>{person?person.name:source==='official'?'官方 IP':'我的 IP'}</strong>{!person&&<><Input aria-label="搜索 IP 人物" placeholder="搜索人物名称或设定" prefix={<Search size={16}/>} allowClear value={search} onChange={e=>setSearch(e.target.value)}/><Select aria-label="筛选素材类别" value={role} onChange={setRole} options={[{value:'all',label:'全部素材'},...Object.entries(ipAssetRoles).filter(([k])=>k!=='history').map(([value,label])=>({value,label}))]}/><Select aria-label="筛选人物属性" allowClear placeholder="人物属性" value={attribute} onChange={setAttribute} options={attributeOptions}/></>}<Button disabled={loading||busy} onClick={onRefresh}>刷新</Button></header>
        {loading?<div className="studio-library-state" role="status">正在读取人物档案…</div>:error?<div className="studio-library-state" role="alert"><p>{error}</p><Button onClick={onRefresh}>重新加载</Button></div>:person&&selected?<>
          <div className="studio-character-navigation"><button type="button" disabled={busy} onClick={()=>setPersonId(undefined)}><ArrowLeft size={15}/>返回人物库</button><span>{index>=0?`${index+1} / ${shown.length}`:'人物详情'}</span><div><button type="button" aria-label="上一个人物" disabled={busy||index<=0} onClick={()=>openPerson(shown[index-1].id)}><ChevronLeft size={18}/></button><button type="button" aria-label="下一个人物" disabled={busy||index<0||index>=shown.length-1} onClick={()=>openPerson(shown[index+1].id)}><ChevronRight size={18}/></button></div></div>
          <div className="studio-character-detail"><div className="studio-character-visuals">
            <section className="studio-character-hero" aria-label="当前选择的素材"><div className="studio-character-hero-label">{ipAssetRoles[ipAssetRole(selected)]}{selected.lookId?'':` · v${selected.version}`}</div><SignedImage src={selected.url} storageKey={selected.storageKey} alt={`${person.name} · ${ipAssetRoles[ipAssetRole(selected)]}`}/><strong>{selected.name}</strong></section>
            <div className="studio-character-reference-row">{visual('主形象',['main'])}{visual('脸部特写',['portrait'])}{visual('表情',['expression'])}</div>
            {visual('人物设定图',['sheet'],true)}{visual('三视图与视角',['three-view','front','side','back'],true)}{visual('服装与细节',['detail','look'],true)}
            {person.assets.some(a=>ipAssetRole(a)==='history')&&<details className="studio-character-history"><summary>历史主形象 · {person.assets.filter(a=>ipAssetRole(a)==='history').length} 个版本</summary>{visual('历史主形象',['history'],true)}</details>}
          </div><aside className="studio-character-info"><section><h3>人物属性</h3><dl><div><dt>来源</dt><dd>{person.main.path==='ai'?'AI 原创':person.main.path==='real'?'真人形象':'未填写'}</dd></div><div><dt>主形象</dt><dd>v{person.main.version}</dd></div>{Object.entries(person.main.attributes||{}).map(([key,value])=><div key={key}><dt>{key}</dt><dd>{value}</dd></div>)}</dl>{!Object.keys(person.main.attributes||{}).length&&<p>尚未填写人物属性</p>}</section>
            <section><h3>人物描述</h3><p className="studio-character-description">{person.main.description||'尚未填写人物描述'}</p></section>
            <section><h3><Volume2 size={16}/>人物声音</h3>{voiceLoading?<p role="status">正在读取声音…</p>:voiceError?<><p role="alert">{voiceError}</p><Button onClick={()=>setVoiceRevision(v=>v+1)}>重读声音</Button></>:voice?<><strong>{voice.name} · v{voice.version}</strong><p>{voice.speaker}{voice.instruct?` · ${voice.instruct}`:''}</p><SignedAudio controls src={voice.demoUrl} storageKey={voice.demoStorageKey}/></>:<p>{person.main.librarySource==='official'?'此官方人物未提供声音。加入我的 IP 后，可为自己的形象配置声音。':'未设置默认声音，可在画布配音后保存给此人物。'}</p>}</section>
            {selected.lookId&&selected.librarySource!=='official'&&<section><label>素材归类<Select aria-label="素材归类" disabled={busy} value={ipAssetRole(selected)} onChange={value=>void classify(value)} options={editableIpAssetRoles.map(value=>({value,label:ipAssetRoles[value]}))}/></label><small>仅整理此素材的类别，保存免费。</small></section>}
          </aside></div>
          <div className="studio-character-use studio-library-use"><p>{ipAssetRole(selected)==='sheet'?'整张设定图会作为角色参考。生成视频前，先用它生成一张单独的镜头画面。':`将“${selected.name}”添加为人物参考，保留所选形象版本。`}</p>{voice&&<small>同时沿用默认人物声音 {voice.name} · v{voice.version}</small>}{actionError&&<p role="alert">{actionError}</p>}<Button type="primary" block loading={importing} disabled={busy} onClick={()=>void importSelected()}>{actionLabel||"添加选中素材到画布"}</Button></div>
        </>:shown.length?<><div className="studio-library-count">{shown.length} 位人物 · 点开查看设定和素材</div><div className="studio-character-grid">{shown.map(c=>{const names=[...new Set(c.assets.filter(a=>!['main','history'].includes(ipAssetRole(a))).map(a=>ipAssetRoles[ipAssetRole(a)]))];const hasVoice=voices?.performers.some(p=>p.avatarId===c.id&&p.voiceId);return <button type="button" className="studio-character-card" key={c.id} aria-label={`查看人物 ${c.name}`} onClick={()=>openPerson(c.id)}><div className="studio-character-cover"><SignedImage src={c.main.url} storageKey={c.main.storageKey} alt={c.name}/><span>v{c.main.version}</span></div><div className="studio-character-card-body"><strong>{c.name}</strong><small>{c.main.path==='real'?'真人形象':c.main.path==='ai'?'AI 原创':'人物'} · {c.assets.filter(a=>ipAssetRole(a)!=='history').length} 张素材</small><p>{names.length?names.slice(0,3).join(' · '):'主形象'}{hasVoice?' · 已有声音':''}</p></div></button>;})}</div></>:<div className="studio-library-state"><UserRound size={28}/><h3>{sourceCharacters.length?'没有符合条件的人物':source==='official'?'官方 IP 正在准备中':'还没有可用人物'}</h3><p>{sourceCharacters.length?'换个名称或素材类别试试。':source==='official'?'平台发布的人物与设定图会出现在这里，可直接引用到当前画布。':'在画布生成并采用主形象后，就能在这里管理和引用。'}</p>{characters.length>0&&<Button onClick={()=>{setSearch('');setPath('all');setRole('all');setAttribute(undefined);}}>清除筛选</Button>}</div>}
      </main>
    </div>
  </Modal>;
}
